extends Node

signal turn_ended
signal user_input_requested
signal new_actor_added
signal character_died
signal character_state_changed
signal character_info_requested

signal character_hp_updated
signal character_deck_updated
signal character_fov_updated

signal floor_map_updated
signal floor_tile_updated

signal stairs_popup_signal

signal notable_occurance

signal camera_move_requested

signal char_stopped_moving

signal inventory_updated
signal item_used
signal new_item_added
signal update_gold
signal item_description_requested
signal item_description_hidden

signal card_selector_requested
signal cards_selected
signal card_info_requested

signal card_reward_cheated

signal event_requested
signal event_concluded

signal wait_button_pressed
signal swap_button_pressed
signal reshuffle_button_pressed
signal defend_button_pressed
